### ISSUE TITLE
レビューのお願い

### ISSUE THREAD

**Issue by tomoasleep** [increments/slacken#1]
@yuku-t @yujinakayama @r7kamura 
コードレビューをお願いします :pray:

**Comment by r7kamura** [comment]
- LICENSEはTomoya Chiba名義が最適か
- scriptフォルダに関する説明は足りているか
- sampleというフォルダ名はexampleというフォルダ名よりも適切か
- コーディング規約はあるか
- READMEの説明はこれで足りているか
- Kernel.#require を、あえてselfがmainではなく::Slackenのコンテキストで呼んでいる意図は何か
- ::Slackenに特異メソッドを生やすのは妥当な判断か
 - つまり、::Slackenを名前空間をつくる以外の目的で利用するのは妥当な判断か
- 最初のversionが、最近のBundlerが自動生成する0.1.0になっているのは適切か
- テスト環境で全てのオブジェクトに対して object.fixture を呼べるようになっているのは意図通りか
- ::DocumentComponentDsl がトップレベルに定義されてるのは適切か
 - 衝突の可能性を考慮する姿勢を見せた方がいいのでは
- `options = children.first.is_a?(Hash) ? children.shift : {}` はlastとpopではないのか
 - Array#extract_optionsの実装を読んだことがあるか
- spec_helperで二度expand_pathを実行しているのは無駄では
- `#fixture` はテスト全体でキャッシュしないとほとんど無意味では
- configurationをcと略すのは分かりづらい
- 一番大事なテストは ::Slacken.translate に対するテストだろうと思うが、論理的には同じ成果物を比較しているだけでテストの要をなしていないのでは
- クラスを参照するときに "Slacken::" を省略したいがためにテスト内でmodule Slacken...と書くのは妥当か
 - 実装の都合でSlackenがclassになったらどうするつもり?
- ::Slacken.convert はtranslateからしか参照されていないがpublicでいいのか

**Comment by tomoasleep** [comment]
> LICENSEはTomoya Chiba名義が最適か

これ実際どうなんだろう、`Increments Inc` の方が適切ってこと？

**Comment by tomoasleep** [comment]
直す際にソースコード改変するのは問題無いと思っている

**Comment by tomoasleep** [comment]
> Kernel.#require を、あえてselfがmainではなく::Slackenのコンテキストで呼んでいる意図は何か

Slackenモジュールが作られた後ならどこでもいいので特に意図はないです。
